### PR TITLE
RUMM-290 Make `Logger` tags and attributes thread safe

### LINKED ISSUE #47: Crash when logging a debug level event via Logger
It appears that in all cases, this occurs shortly after launch / after Logger is created.

Crash details:
```
Thread 7 Crashed:
0   libswiftCore.dylib            	0x000000020b96f7ec swift_isUniquelyReferenced_nonNull_native + 0
1   Datadog                       	0x000000010969d7d0 specialized Dictionary.merging(_:uniquingKeysWith:) + 64 (<compiler-generated>:0)
2   Datadog                       	0x000000010969a024 Logger.debug(_:attributes:) + 152
3   InstaShopper                  	0x0000000103cc40c8 DatadogWriter.writeMessage(_:logLevel:) + 992
```

Redacted crash report included in zip file:

[2020-03-11_21-34-05.9183_-0400-d9f8257d00b30d86bce2bfac00812dcd649fff30.crash.zip](https://github.com/DataDog/dd-sdk-ios/files/4330593/2020-03-11_21-34-05.9183_-0400-d9f8257d00b30d86bce2bfac00812dcd649fff30.crash.zip)

Last commit in version we are currently using is 5eb1ecc63d69bd8d728dc8f675ceb9aa6c1b0a81

### PR DESCRIPTION
**Pull request by ncreated**
### What and why?

📦 This fixes #47 

`Logger` tags and attributes were not thread safe, so when mutated parallelly by different threads, the SDK was resulting with a crash on `loggerTags` and `loggerAttributes` access.

### How?

I added basic thread safety using logger-specific `DispatchQueue` with `.sync {}` (writes) and `.async {}` (reads) synchronization.

Following this great [post from Matt Gallagher](http://www.cocoawithlove.com/blog/2016/06/02/threads-and-mutexes.html) this might be not the most performant way of synchronization, but I checked benchmark results and they are still acceptable:

Screenshot 2020-03-17 at 18 48 48

### Review checklist

- [x] Feature or bugfix MUST have appropriate tests (unit, integration)
- [x] Make sure each commit and the PR mention the Issue number or JIRA reference

### CODE REVIEW

File: Sources/Datadog/Logger.swift [hunk 1]
```diff
@@ -80,9 +80,12 @@ public class Logger {
     private var loggerAttributes: [String: Encodable] = [:]
     /// Taggs associated with every log.
     private var loggerTags: Set<String> = []
+    /// Queue ensuring thread-safety of the `Logger`. It synchronizes tags and attributes mutation.
+    private let queue: DispatchQueue
 
-    init(logOutput: LogOutput) {
+    init(logOutput: LogOutput, queue: DispatchQueue) {
```
Comment (buranmert) [inline Sources/Datadog/Logger.swift]: as `queue` is an implementation detail in `Logger`, i think it should not be exposed in any way.

because
• interference from outside may break its function (ie: sync'ing read-write within `Logger`)
• ideally, we need to test all possible `DispatchQueue` configurations

so, i propose 
• passing `identifier: String` to `init` and 
• adding `var identifier { queue.identifier }` public computed property

```swift
var identifier: String { queue.label }
...
init(identifier: String, ...) {
  queue = DispatchQueue(label: identifier, qos: .userInteractive)
  ...
}
```

Comment (ncreated) [reply Sources/Datadog/Logger.swift]: Indeed, `DispatchQueue` dependency is "too wide" and we can narrow it with an "identifier".

However, I don't see the reason to expose public `identifier: String` from the `Logger` - why this might be useful for the user? As a rule of thumb 👍 - the less things we expose as `public` the better, as it means less hassle with backward compatibility.

Changes pushed 🚀, let me know WDYT.

Comment (buranmert) [reply Sources/Datadog/Logger.swift]: super 💯 

me neither, i don't see how it might be useful; as another rule of thumb, i think the user should get what they give.
but you are right, backward compatibility overshadows my argument 👍 

then `label` (or `queueLabel` even better?) sounds better than `identifier` as the user cannot identify `Logger` with it?

File: Sources/Datadog/Logger.swift [hunk 2]
```diff
@@ -203,25 +214,34 @@ public class Logger {
...
+            self.loggerTags.remove(tag)
+        }
     }
 
     // MARK: - Private
 
     private func log(level: LogLevel, message: String, messageAttributes: [String: Encodable]?) {
-        let combinedAttributes = loggerAttributes.merging(messageAttributes ?? [:]) { _, messageAttributeValue in
-            return messageAttributeValue // use message attribute when the same key appears also in logger attributes
+        let combinedAttributes = queue.sync {
```
Comment (mariusc83) [inline Sources/Datadog/Logger.swift]: I am thinking here...not sure exactly how the queue works but what if I add a tag and I call `log` after ? The **add-tag** action will be dispatched asynchronously in the queue while the log will be executed synchronously...meaning that you might lose some tags or attributes there right ?  Why not making all "sync" ?

File: Tests/DatadogTests/Datadog/LoggerTests.swift [hunk 3]
```diff
@@ -408,4 +408,31 @@ class LoggerTests: XCTestCase {
             .verifyNoLogsSent()
             .destroy()
     }
+
+    // MARK: - Thread safety
+
+    func testRandomlyCallingDifferentAPIsConcurrentlyDoesNotCrash() {
```
Comment (mariusc83) [inline Tests/DatadogTests/Datadog/LoggerTests.swift]: nice ;)

File: Sources/Datadog/Logger.swift (hunk 2 above)
Comment (buranmert) [reply Sources/Datadog/Logger.swift]: let me take some burden off @ncreated's shoulders :) 

by default, `DispatchQueue`s are serial, tasks are scheduled for immediate execution regardless `sync` or `async` is used.

• if we call `sync`, current thread waits until the queue finishes execution
• if we call `async`, current thread continues without waiting for the queue

so, `async` is supposed to give us a performance gain without sacrificing correctness
you also can find more info [here](https://developer.apple.com/documentation/dispatch/dispatchqueue)

Comment (mariusc83) [reply Sources/Datadog/Logger.swift]: Tks, like I was suspecting, the DispatchQueue handles everything for you ;)

File: Sources/Datadog/Logger.swift (hunk 1 above)
Comment (ncreated) [reply Sources/Datadog/Logger.swift]: > then, wouldn't label (or even queueLabel?) sound better than identifier as the user cannot identify Logger with it?

I like the "identifier" as it somehow highlights the behavioral usage of this variable (it's to identify the logger). We might also want to use it for other things in the future. Anyway, IMO it's good enough 💪.

File: Tests/DatadogTests/Datadog/LoggerTests.swift (hunk 3 above)
Comment (ncreated) [reply Tests/DatadogTests/Datadog/LoggerTests.swift]: 💪
