### PR TITLE
RUM-12702 Build xcframework with and without arm64e

### LINKED ISSUE #2560: Error in App Store Connect with Xcode 26
### Describe the bug

When we generate a build with Xcode `26.0.1,` the build is successful.

However, when we upload it to Apple Store Connect (TestFlight), it throws an error:

Image

--

> **90208: Invalid Bundle.** The bundle Naranja X.app/Frameworks/DatadogCore.framework does not support the minimum OS Version specified in the Info.plist.
>
> **91011: Invalid architecture.** The ios 26 SDK or later is required for an arm64e slice. The bundle executable in “Naranja X.app/Frameworks/DatadogSessionReplay.framework” contains an arm64e slice with the ios 18.2 SDK.
>
> **91011: Invalid architecture.** The ios 26 SDK or later is required for an arm64e slice. The bundle executable in “Naranja X.app/Frameworks/DatadogRUM.framework” contains an arm64e slice with the ios 18.2 SDK.
>
> **90208: Invalid Bundle.** The bundle Naranja X.app/Frameworks/DatadogCrashReporting.framework does not support the minimum OS Version specified in the Info.plist.
>
> **91011: Invalid architecture.** The ios 26 SDK or later is required for an arm64e slice. The bundle executable in “Naranja X.app/Frameworks/DatadogInternal.framework” contains an arm64e slice with the ios 18.2 SDK.
>
> **90208: Invalid Bundle.** The bundle Naranja X.app/Frameworks/DatadogLogs.framework does not support the minimum OS Version specified in the Info.plist.
>
> **91011: Invalid architecture.** The ios 26 SDK or later is required for an arm64e slice. The bundle executable in “Naranja X.app/Frameworks/DatadogLogs.framework” contains an arm64e slice with the ios 18.2 SDK.
>
> **91011: Invalid architecture.** The ios 26 SDK or later is required for an arm64e slice. The bundle executable in “Naranja X.app/Frameworks/DatadogCrashReporting.framework” contains an arm64e slice with the ios 18.2 SDK.
>
> **91011: Invalid architecture.** The ios 26 SDK or later is required for an arm64e slice. The bundle executable in “Naranja X.app/Frameworks/DatadogCore.framework” contains an arm64e slice with the ios 18.2 SDK.
>
> **90208: Invalid Bundle.** The bundle Naranja X.app/Frameworks/DatadogInternal.framework does not support the minimum OS Version specified in the Info.plist.
>
> **90208: Invalid Bundle.** The bundle Naranja X.app/Frameworks/DatadogRUM.framework does not support the minimum OS Version specified in the Info.plist.
>
> **90208: Invalid Bundle.** The bundle Naranja X.app/Frameworks/DatadogSessionReplay.framework does not support the minimum OS Version specified in the Info.plist.`

--

When we build the app with Xcode 16.X, and upload to Apple Store Connect, the build is accepted by Apple. But with Xcode 26.X is rejected.

We think that the `.xcframework` is not being correctly supported in Xcode 26 builds to be uploaded and accepted by Apple Store Connect.

### Reproduction steps

1. Build an `.ipa` of the app with the Datadog SDK integrated with `.xcframework`. The `.ipa` must be generated with Xcode 26.0.1.
2. Upload to App Store Connect.

### SDK logs

-

### Expected behavior

Can upload the app with the Datadog SDK integrated with `.xcframework` and the app builded with Xcode 26.X, to the App Store Connect and that the app not be rejected.

### Affected SDK versions

2.X.X

### Latest working SDK version

2.30.2

### Did you confirm if the latest SDK version fixes the bug?

Yes

### Integration Methods

XCFramework

### Xcode Version

Xcode 26.0.1

### Swift Version

Swift 5.10

### MacOS Version

macOS 15.6 Sequoia

### Deployment Target

iOS 15

### Device Information

_No response_

### Other relevant information

_No response_

### PR DESCRIPTION
**Pull request by maxep**
### What and why?

Changes the release tooling to support building and distributing XCFrameworks both with and without the arm64e architecture slice.

Fixes #2560

When building with Xcode 26.x, App Store Connect rejects the builds with error 91011, stating that arm64e slices require iOS SDK 26 or later, but the Datadog XCFrameworks contain arm64e slices compiled with iOS SDK 18.2.

Until the SDK is rebuilt with Xcode 26, users building with Xcode 26+ need a version without arm64e to successfully submit to App Store Connect.

This PR provides both versions in releases:
- `Datadog-with-arm64e.xcframework.zip` - Full version with all architectures (for Xcode 16.x builds)
- `Datadog.xcframework.zip` - Version without arm64e (for Xcode 26+ builds and App Store Connect submission)

### How?

**New Scripts:**
1. **[tools/release/remove-arm64e-from-xcframework.sh](tools/release/remove-arm64e-from-xcframework.sh)** - Core processing script that removes arm64e slices from XCFramework binaries using `lipo -remove arm64e`
2. **[tools/release/remove-arm64e-from-release.sh](tools/release/remove-arm64e-from-release.sh)** - Release management script that downloads an existing GitHub release asset, processes it to create both versions, and uploads them back with user confirmation

**Modified Scripts:**
- **[tools/release/build.sh](tools/release/build.sh)** - Now creates both XCFramework versions during the build process by copying the original and processing the copy
- **[tools/release/publish-github.sh](tools/release/publish-github.sh)** - Updated to upload both XCFramework zip files to GitHub releases

### Review checklist
- [x] Feature or bugfix MUST have appropriate tests (unit, integration)
- [x] Make sure each commit and the PR mention the Issue number or JIRA reference
- [x] Add CHANGELOG entry for user facing changes
- [ ] Add Objective-C interface for public APIs (see our [guidelines](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/3157787243/RFC+-+Modular+Objective-C+Interface#Recommended-solution) (internal) and run `make api-surface`)

### CODE REVIEW

File: tools/release/publish-github.sh [hunk 1]
```diff
@@ -2,60 +2,58 @@
...
-        gh release upload $tag "$GH_ASSET_PATH" --repo "$REPO_NAME" ${ghoptions[@]}
+        gh release upload "$tag" "$GH_ASSET_WITH_ARM64E" "$GH_ASSET_WITHOUT_ARM64E" \
+            --repo "$REPO_NAME" ${ghoptions[@]}
+        echo_succ "Uploaded successfully"
     fi
 }
 
-echo_info "Publishing '$GH_ASSET_PATH' to '$tag' release in '$REPO_NAME'"
-echo_info "▸ Using DRY_RUN = $DRY_RUN"
-echo_info "▸ Using OVERWRITE_EXISTING = $OVERWRITE_EXISTING"
```
Comment (ncreated) [inline tools/release/publish-github.sh:57]: Any reason to remove these logs? They're quite handy to understand the configuration of CI job / local run.

Comment (maxep) [reply tools/release/publish-github.sh:57]: Not really, we don't have a single `GH_ASSET_PATH` anymore and it was a bit redundant with the `echo_subtitle "Uploading assets to '$tag' release"` from the `upload` function. I can re-add the full context 👍

Comment (maxep) [reply tools/release/publish-github.sh:57]: Done!

**Review by ncreated — APPROVED** [review]
