### PR TITLE
Fix xcframework GH assets

### LINKED ISSUE #1318: XCFramework - zip contained on release is not found by Carthage
### Change name of artifact

Carthage can download the xcframework from github releases. But the name should be DataDog.xcframework.zip instead of DataDog.zip.

See https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-zip-files

### PR DESCRIPTION
**Pull request by maxep**
### What and why?

Update GH asset name for pre-build binaries following [Carthage requirements](https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-zip-files).

fix #1318

### How?

With v2 and module stability enabled, GH assets will be named `Datadog.xcframework.zip`.
Prior to v2 and since we were not compliant with Carthage, we can always include the Xcode version in the asset name. The `add_xcode_version_to_github_asset` parameter is now unnecessary and has been removed.

### Review checklist
- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)
- [ ] Make sure each commit and the PR mention the Issue number or JIRA reference
- [ ] Add CHANGELOG entry for user facing changes

### Custom CI job configuration (optional)
- [ ] Run unit tests
- [ ] Run integration tests
- [ ] Run smoke tests

### CODE REVIEW

File: Package.swift [hunk 1]
```diff
@@ -29,10 +29,6 @@ let package = Package(
             name: "DatadogRUM",
             targets: ["DatadogRUM"]
         ),
-        .library(
-            name: "DatadogSessionReplay",
-            targets: ["DatadogSessionReplay"]
-        ),
```
Comment (maxep) [inline Package.swift:35]: This was exposed for `dogfooding`.

File: tools/distribution/src/utils.py [hunk 2]
```diff
@@ -71,9 +71,11 @@ def read_sdk_version() -> str:
     Reads SDK version from 'Sources/Datadog/Versioning.swift'.
     """
     file = 'DatadogCore/Sources/Versioning.swift'
-    version_regex = r'^.+\"([0-9]+\.[0-9]+\.[0-9]+[\-a-z0-9]*)\"'  # e.g. 'internal let __sdkVersion = "1.8.0-beta1"'
```
Comment (maxep) [inline tools/distribution/src/utils.py:74]: This regex is no longer valid following 856ed98b034713fc340452ff8d26a2ebc3834dec
It has been replace with [VERSION_PATTERN](https://packaging.pypa.io/en/latest/version.html#packaging.version.VERSION_PATTERN)

File: tools/distribution/src/utils.py [hunk 3]
```diff
@@ -71,9 +71,11 @@ def read_sdk_version() -> str:
...
 
-    versions: [str] = []
+    # https://packaging.pypa.io/en/latest/version.html#packaging.version.VERSION_PATTERN
+    version_regex = re.compile(r'^.+\"' + VERSION_PATTERN + r'\"$', re.VERBOSE | re.IGNORECASE) # e.g. 'internal let __sdkVersion = "1.8.0-beta.1"
```
Comment (ganeshnj) [inline tools/distribution/src/utils.py:76]: for such trivial case, we should use simply parse the string than taking a dependency 

1.8.0-beta1
```
split by -
- 1.8.0
  - split by .
    - major: 1
    - minor: 8
    - patch: 0 
- beta1
    - read from back until there is digit
      - beta
      - 1
```

File: tools/distribution/release.py [hunk 4]
```diff
@@ -73,9 +72,6 @@
         if only_cocoapods and overwrite_github:
             raise Exception('`--overwrite-github` and `--only-cocoapods` cannot be used together.')
 
-        if only_cocoapods and add_xcode_version_to_github_asset:
```
Comment (ganeshnj) [inline tools/distribution/release.py:76]: image
can we remove ^^ also?

**Review by ncreated — APPROVED** [review]
Looks good 👍 - let's also update [CI setup for iOS SDK](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/2436007444/CI+setup+for+iOS+SDK#tagged_commit) (internal) accordingly.

File: tools/distribution/src/utils.py (hunk 3 above)
Comment (maxep) [reply tools/distribution/src/utils.py:76]: The dependency was already introduced in 856ed98b034713fc340452ff8d26a2ebc3834dec and I think it is best to rely on the same pattern everywhere 👍

File: tools/distribution/release.py (hunk 4 above)
Comment (maxep) [reply tools/distribution/release.py:76]: good catch!
