### PR TITLE
RUMM-894 URLProvider fixed for illegal chars

### LINKED ISSUE #316: Crash when custom service name contains spaces
When Datadog RUM is configured using a custom service name which contains characters not permitted in URL query strings (such as a space), the library will crash.

I'm using version `1.4.0-beta1`.

Steps to reproduce:

1. Configure Datadog for RUM and set a custom service name:

```swift
Datadog.initialize(
    appContext: .init(),
    configuration:
        Datadog.Configuration
            .builderUsing(
                rumApplicationID: "<RUM Application ID>",
                clientToken: "<Client Token>",
                environment: "sandbox"
            )
            .set(serviceName: "My App")
            .build()
)
Global.rum = RUMMonitor.initialize()
```

2. Run the app and Datadog should crash with the following error:

```
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2041daf2 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48
	2   Foundation                          0x00007fff2085cb21 __57-[__NSConcreteURLComponents setPercentEncodedQueryItems:]_block_invoke + 0
	3   libswiftFoundation.dylib            0x0000000106eaf947 $s10Foundation13URLComponentsV10queryItemsSayAA12URLQueryItemVGSgvsTf4gn_nTm + 311
	4   libswiftFoundation.dylib            0x0000000106eaadb5 $s10Foundation13URLComponentsV24percentEncodedQueryItemsSayAA12URLQueryItemVGSgvs + 21
	5   Datadog                             0x0000000105b51b42 $s7Datadog17UploadURLProviderC3url10Foundation3URLVvg + 946
	6   Datadog                             0x0000000105b52d18 $s7Datadog12DataUploaderC17createRequestWith33_B0B50AAFF8A14F152AB4165520ED0E9ALL4data10Foundation10URLRequestVAG0B0V_tF + 248
	7   Datadog                             0x0000000105b52a0e $s7Datadog12DataUploaderC6upload4dataAA0B12UploadStatusO10Foundation0B0V_tF + 270
	8   Datadog                             0x0000000105b4ee66 $s7Datadog16DataUploadWorkerC012scheduleNextC004_2E3G27D1790FB5C692514696637CC9BCBLL5afterySd_tFyycfU_ + 3078
	9   Datadog                             0x0000000105b18120 $sIeg_IeyB_TR + 48
	10  libdispatch.dylib                   0x00000001073389c8 _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x000000010733b316 _dispatch_continuation_pop + 557
	12  libdispatch.dylib                   0x000000010734ee8b _dispatch_source_invoke + 2205
	13  libdispatch.dylib                   0x000000010733f0ad _dispatch_lane_serial_drain + 307
	14  libdispatch.dylib                   0x000000010733ff67 _dispatch_lane_invoke + 439
	15  libdispatch.dylib                   0x000000010734bde2 _dispatch_workloop_worker_thread + 882
	16  libsystem_pthread.dylib             0x00007fff5e73d499 _pthread_wqthread + 314
	17  libsystem_pthread.dylib             0x00007fff5e73c467 start_wqthread + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSURLComponents setPercentEncodedQueryItems:]: invalid characters in percentEncodedQueryItems'
terminating with uncaught exception of type NSException
```

### PR DESCRIPTION
**Pull request by buranmert**
### What and why?

Fixes #316 

### How?

Wrong property of `URLComponents` (`percentEncodedQueryItems`) was used in `URLProvider`
It is fixed by being replaced with the correct method (`queryItems`)

### Review checklist

- [x] Feature or bugfix MUST have appropriate tests (unit, integration)
- [x] Make sure each commit and the PR mention the Issue number or JIRA reference

### CODE REVIEW

File: Tests/DatadogTests/Datadog/Core/Upload/DataUploaderTests.swift [hunk 1]
```diff
@@ -46,6 +46,15 @@ class DataUploadURLProviderTests: XCTestCase {
         dateProvider.advance(bySeconds: 9.999)
         XCTAssertEqual(urlProvider.url, URL(string: "https://api.example.com/v1/endpoint/abc?ddsource=ios&batch_time=1576404009999"))
     }
+
+    func testIllegalCharactersInQueryItemsDontCrash() throws {
```
Comment (ncreated) [inline Tests/DatadogTests/Datadog/Core/Upload/DataUploaderTests.swift:50]: Whitespaces are not "illegal" and the expected behaviour is not to "don't crash" (we could say so for all tests). To be more precise:
```suggestion
    func testItEscapesWhitespacesInQueryItems() throws {
```

**Review by ncreated — APPROVED** [review]
