### PR TITLE
Fix privacy manifest collision

### LINKED ISSUE #1665: Privacy manifest causing collisions through CocoaPods
The `2.7.0` release added a privacy manifest, but its current setup with CocoaPods is causing collisions with other privacy manifest files as you can see below:

image

I believe this is because the `PrivacyInfo.xcprivacy` is referenced as a `resource` in the [podspec](https://github.com/DataDog/dd-sdk-ios/blob/9faa46ce5e93ae453cebb623771a926b44f8ac23/DatadogCore.podspec#L25) instead of using `resource_bundle`. The latter would avoid collisions by putting the privacy manifest file in subfolders for each dependency, instead of going in the app bundle's root. More context on this [here](https://github.com/google/promises/pull/226#discussion_r1447871477). I think the fix would be to simple swap `resource` with `resource_bundle` here.

### PR DESCRIPTION
**Pull request by maxep**
### What and why?

When using static linkage in CocoaPods with `use_frameworks! :linkage => :static`. The pod's resource gets copied at root of the app bundle, resulting in collision with the app's `PrivacyInfo.xcprivacy`.

Resolve #1665

### How?

Use `resource_bundle` to keep the `PrivacyInfo.xcprivacy` in it own bundle.

The smoke tests apps now all define privacy-manifest to catch any collision.

### Review checklist
- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)
- [ ] Make sure each commit and the PR mention the Issue number or JIRA reference
- [ ] Add CHANGELOG entry for user facing changes

### Custom CI job configuration (optional)
- [ ] Run unit tests for Core, RUM, Trace, Logs, CR and WVT
- [ ] Run unit tests for Session Replay
- [ ] Run integration tests
- [x] Run smoke tests
- [ ] Run tests for `tools/`

### CODE REVIEW

File: dependency-manager-tests/carthage/App/ViewController.swift [hunk 1]
```diff
@@ -41,13 +41,6 @@ internal class ViewController: UIViewController {
         RUM.enable(with: .init(applicationID: "app-id"))
         RUMMonitor.shared().startView(viewController: self)
 
-        // DDURLSessionDelegate APIs must be visible:
-        _ = DDURLSessionDelegate()
-        _ = DatadogURLSessionDelegate()
-        class CustomDelegate: NSObject, __URLSessionDelegateProviding {
-            var ddURLSessionDelegate: DatadogURLSessionDelegate { DatadogURLSessionDelegate() }
-        }
```
Comment (ncreated) [inline dependency-manager-tests/carthage/App/ViewController.swift:49]: q/ Why this removal? Due to deprecation warnings treated as build error?

**Review by ncreated — APPROVED** [review]
👌 Great we cover this in smoke tests now 👍

File: dependency-manager-tests/carthage/App/ViewController.swift (hunk 1 above)
Comment (maxep) [reply dependency-manager-tests/carthage/App/ViewController.swift:49]: Yes, and because it's deprecated anyway.
